---
title: "BS Auswertungen"
author: "Rudi Farys"
date: "Sunday, September 28, 2014"
output: html_document
---

### Libraries
```{r libs}
library(foreign)
library(ggplot2)
library(dplyr)
library(knitr)
library(ineq)
library(ebal)
library(IC2)
```

### Data
```{r data}
setwd("G:/stick/")
#ju <- read.csv("jura/taxdata_JU.csv")
#bs <- read.dta("basel/taxdata_BS.dta")
#save(bs, file="G:/stick/basel/taxdata_BS.Rdata")
load("G:/stick/basel/taxdata_BS.Rdata")
bs$household <- NA
bs$agegroup <- NA
#ju$alterskategorie<-NA
#ju$household <- NA
#ju$agegroup <- NA
bs <- within(bs, {
agegroup <-NA
agegroup[alterskategorie=="00_26"]<-1
agegroup[alterskategorie=="26_35"]<-2
agegroup[alterskategorie=="36_45"]<-2
agegroup[alterskategorie=="46_55"]<-2
agegroup[alterskategorie=="56_65"]<-2
agegroup[alterskategorie=="66_75"]<-3
agegroup[alterskategorie=="76_85"]<-3
agegroup[alterskategorie=="86_95"]<-3
agegroup[alterskategorie=="95_+"]<-3

agegroup<-factor(agegroup,
                      levels=c(1,2,3),
                      labels=c("18-25","26-65","66+"))

agegroup_det <-NA
agegroup_det[alterskategorie=="00_26"]<-1
agegroup_det[alterskategorie=="26_35"]<-2
agegroup_det[alterskategorie=="36_45"]<-3
agegroup_det[alterskategorie=="46_55"]<-4
agegroup_det[alterskategorie=="56_65"]<-5
agegroup_det[alterskategorie=="66_75"]<-6
agegroup_det[alterskategorie=="76_85"]<-7
agegroup_det[alterskategorie=="86_95"]<-7
agegroup_det[alterskategorie=="95_+"]<-7
agegroup_det<-factor(agegroup_det,
                      levels=c(1,2,3,4,5,6,7),
                      labels=c("18-25","26-35","36-45","46-55","56-65","66-75","76+"))

# Housholdstructure
household < NA
household[ZIVILSTAND=="verheiratet" & anzahl_kinder==0]<-1
household[ZIVILSTAND=="verheiratet" & anzahl_kinder>0]<-2
household[ZIVILSTAND=="ledig" 
                & anzahl_kinder==0 & GESCHLECHT_P1=="Mann"]<-3
household[ZIVILSTAND=="geschieden/getrennt"
                & anzahl_kinder==0 & GESCHLECHT_P1=="Mann"]<-3
household[ZIVILSTAND=="verwittwet"
                & anzahl_kinder==0 & GESCHLECHT_P1=="Mann"]<-3
household[ZIVILSTAND=="ledig" 
                & anzahl_kinder==0 & GESCHLECHT_P1=="Frau"]<-4
household[ZIVILSTAND=="geschieden/getrennt" 
                & anzahl_kinder==0 & GESCHLECHT_P1=="Frau"]<-4
household[ZIVILSTAND=="verwittwet" 
                & anzahl_kinder==0 & GESCHLECHT_P1=="Frau"]<-4
household[ZIVILSTAND=="ledig"
                & anzahl_kinder>1 & GESCHLECHT_P1=="Mann"]<-5
household[ZIVILSTAND=="geschieden/getrennt"
                & anzahl_kinder>1 & GESCHLECHT_P1=="Mann"]<-5
household[ZIVILSTAND=="verwittwet"
                & anzahl_kinder>1 & GESCHLECHT_P1=="Mann"]<-5
household[ZIVILSTAND=="ledig"
                & anzahl_kinder>1 & GESCHLECHT_P1=="Frau"]<-6
household[ZIVILSTAND=="geschieden/getrennt"
                & anzahl_kinder>1 & GESCHLECHT_P1=="Frau"]<-6
household[ZIVILSTAND=="verwittwet"
                & anzahl_kinder>1 & GESCHLECHT_P1=="Frau"]<-6

household<-factor(household,
                       levels=c(1,2,3,4,5,6),
                       labels=c("Married with Kid(s)","Married without Kid(s)",
                                "Single man","Single women","Single dad","Single mom"))
reineinkommen[steuerjahr>2004]<-z739_reineinkommen[steuerjahr>2004]
})
# Einkommen mit 0 setzen wir auf 1 CHF, damit Theil berechnet werden kann und der Logarithmus gezogen werden kann
bs$reineinkommen[bs$reineinkommen==0]<-1


#ju <- within(ju, {
#ageP1<-(PERIODE-GEBURTSJAHR_P1)
#ageP2<-(PERIODE-GEBURTSJAHR_P2)


# Agegroups (according to age of dossier carrier)

#agegroup[ageP1<26]<-1
#agegroup[ageP1>25 & ageP1<66 ]<-2
#agegroup[ageP1>65]<-3

#agegroup<-factor(agegroup,
#                       levels=c(1,2,3),
#                       labels=c("18-25","26-65","66+"))

# Agegroups - detailled
#alterskategorie[ageP1<26]<-1
#alterskategorie[ageP1>25 & ageP1<36 ]<-2
#alterskategorie[ageP1>35 & ageP1<46 ]<-3
#alterskategorie[ageP1>45 & ageP1<56 ]<-4
#alterskategorie[ageP1>55 & ageP1<66 ]<-5
#alterskategorie[ageP1>65 & ageP1<76 ]<-6
#alterskategorie[ageP1>75 & ageP1<86 ]<-7
#alterskategorie[ageP1>85 & ageP1<96 ]<-8
#alterskategorie[ageP1>95]<-9

#alterskategorie<-factor(alterskategorie,
#                       levels=c(1,2,3,4,5,6,7,8,9),
#                       labels=c("18-25","26-35","36-45","46-55","56-65","66-75","76-85","86-95","95_+"))


# Housholdstructure
#household[ZIVILSTAND=="verheiratet" & ANZAHL_KINDER==0]<-1
#household[ZIVILSTAND=="verheiratet" & ANZAHL_KINDER>0]<-2
#household[ZIVILSTAND=="ledig" 
#                & ANZAHL_KINDER==0 & GESCHLECHT_P1==0]<-3
#household[ZIVILSTAND=="geschieden/getrennt"
#                & ANZAHL_KINDER==0 & GESCHLECHT_P1==0]<-3
#household[ZIVILSTAND=="verwittwet"
#                & ANZAHL_KINDER==0 & GESCHLECHT_P1==0]<-3
#household[ZIVILSTAND=="ledig" 
#                & ANZAHL_KINDER==0 & GESCHLECHT_P1==1]<-4
#household[ZIVILSTAND=="geschieden/getrennt" 
#                & ANZAHL_KINDER==0 & GESCHLECHT_P1==1]<-4
#household[ZIVILSTAND=="verwittwet" 
#                & ANZAHL_KINDER==0 & GESCHLECHT_P1==1]<-4
#household[ZIVILSTAND=="ledig"
#                & ANZAHL_KINDER>1 & GESCHLECHT_P1==0]<-5
#household[ZIVILSTAND=="geschieden/getrennt"
#                & ANZAHL_KINDER>1 & GESCHLECHT_P1==0]<-5
#household[ZIVILSTAND=="verwittwet"
#                & ANZAHL_KINDER>1 & GESCHLECHT_P1==0]<-5
#household[ZIVILSTAND=="ledig"
#                & ANZAHL_KINDER>1 & GESCHLECHT_P1==1]<-6
#household[ZIVILSTAND=="geschieden/getrennt"
#                & ANZAHL_KINDER>1 & GESCHLECHT_P1==1]<-6
#household[ZIVILSTAND=="verwittwet"
#                & ANZAHL_KINDER>1 & GESCHLECHT_P1==1]<-6

#household<-factor(household,
#                        levels=c(1,2,3,4,5,6),
#                        labels=c("Married with Kid(s)","Married without Kid(s)",
#                                 "Single man","Single women","Single dad","Single mom"))

# Jahre Steuerperiode 

#steuerjahr<-PERIODE

#})

bs91_11 <- filter(bs, steuerjahr%in%c(1991,2011)) %.% select(steuerjahr, household, reineinkommen,agegroup,alterskategorie,agegroup_det) %.% mutate(steuerjahr=factor(steuerjahr))
#ju06_12 <- filter(ju, steuerjahr%in%c(2006,2012)&stbeink_BUND>=0) %.% select(steuerjahr, household, stbeink_BUND,agegroup,alterskategorie)%.% mutate(steuerjahr=factor(steuerjahr))

# real einkommen. wir gewichten 1991 mit dem preisindex von 2011
#bs91_11$reineinkommen[bs91_11$steuerjahr=="1991"] <- bs91_11$reineinkommen[bs91_11$steuerjahr=="1991"]*99.342/79.9968
# enspricht juni 1991 vs juni 2011
```

### Optionen
```{r opts}
opts_chunk$set(fig.width=10, fig.height=10) 
```

### Density Plots

#### Basel 1991 vs 2011

```{r}
# Basel Households
p50s <- aggregate(log(bs91_11$reineinkommen)~bs91_11$household+factor(bs91_11$steuerjahr),FUN=median,na.rm=TRUE)
names(p50s) <- c("household","steuerjahr","log_income")
p50s <- p50s[order(p50s$household),]
theils <- aggregate(bs91_11$reineinkommen~bs91_11$household+factor(bs91_11$steuerjahr),FUN=Theil)
names(theils) <- c("household","steuerjahr","Theil")
theils <- theils[order(theils$household),]

ggplot(filter(bs91_11,!is.na(household)),aes(x=log(reineinkommen),fill=steuerjahr))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
  geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
  geom_text(data=theils, position=position_dodge(width=10), aes(size=0.5,x = 11, y = 0.65, color=steuerjahr, label = paste("Theil:",round(theils$Theil,2))))+
geom_text(data=p50s, position=position_dodge(width=10), aes(size=0.5,x = 11, y = 0.45, color=steuerjahr, label = paste("p50:",round(exp(p50s$log_income),0))))+
  facet_wrap(~household,ncol=1)+
  scale_fill_manual(values=c("1991"="blue","2011"="red" )) +
  scale_color_manual(values=c("1991"="blue","2011"="red" )) +
  ggtitle("Basel-City: log net income by tax period and household situation")+
  xlab("log net income")+
  theme_bw()

# Basel: Agegroups
p50s <- aggregate(log(bs91_11$reineinkommen)~bs91_11$agegroup+factor(bs91_11$steuerjahr),FUN=median,na.rm=TRUE)
names(p50s) <- c("agegroup","steuerjahr","log_income")
p50s <- p50s[order(p50s$agegroup),]
theils <- aggregate(bs91_11$reineinkommen~bs91_11$agegroup+factor(bs91_11$steuerjahr),FUN=Theil)
names(theils) <- c("agegroup","steuerjahr","Theil")
theils <- theils[order(theils$agegroup),]
ggplot(bs91_11,aes(x=log(reineinkommen),fill=steuerjahr))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
  geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
geom_text(data=theils, position=position_dodge(width=10), aes(x = 11, y = 0.6, color=steuerjahr, label = paste("Theil:",round(theils$Theil,2))))+
geom_text(data=p50s, position=position_dodge(width=10), aes(x = 11, y = 0.5, color=steuerjahr, label = paste("p50:",round(exp(p50s$log_income),0))))+
  facet_wrap(~agegroup,ncol=1)+
  scale_fill_manual(values=c("1991"="blue","2011"="red" )) +
  scale_color_manual(values=c("1991"="blue","2011"="red" )) +
  ggtitle("Basel-City: log net income by tax period and agegroup")+
  xlab("log net income")+
  theme_bw()


# Basel: Agegroups detailed
p50s <- aggregate(log(bs91_11$reineinkommen)~bs91_11$alterskategorie+factor(bs91_11$steuerjahr),FUN=median,na.rm=TRUE)
names(p50s) <- c("alterskategorie","steuerjahr","log_income")
p50s <- p50s[order(p50s$alterskategorie),]
theils <- aggregate(bs91_11$reineinkommen~bs91_11$alterskategorie+factor(bs91_11$steuerjahr),FUN=Theil)
names(theils) <- c("alterskategorie","steuerjahr","Theil")
theils <- theils[order(theils$alterskategorie),]
ggplot(bs91_11,aes(x=log(reineinkommen),fill=steuerjahr))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
  geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
geom_text(data=theils, position=position_dodge(width=10), aes(x = 11, y = 0.62, color=steuerjahr, label = paste("Theil:",round(theils$Theil,2))))+
geom_text(data=p50s, position=position_dodge(width=10), aes(x = 11, y = 0.48, color=steuerjahr, label = paste("p50:",round(exp(p50s$log_income),0))))+
  facet_wrap(~alterskategorie,ncol=1)+
  scale_fill_manual(values=c("1991"="blue","2011"="red" )) +
  scale_color_manual(values=c("1991"="blue","2011"="red" )) +
  ggtitle("Basel-City: log net income by tax period and agegroup (detailed)")+
  xlab("log net income")+
  theme_bw()

```

#### Jura 2006 vs 2012

```{r eval=FALSE}
# JURA Households
p50s <- aggregate(log(ju06_12$stbeink_BUND)~ju06_12$household+factor(ju06_12$steuerjahr),FUN=median,na.rm=TRUE)
names(p50s) <- c("household","steuerjahr","log_income")
p50s <- p50s[order(p50s$household),]
theils <- aggregate(ju06_12$stbeink_BUND~ju06_12$household+factor(ju06_12$steuerjahr),FUN=Theil)
names(theils) <- c("household","steuerjahr","Theil")
theils <- theils[order(theils$household),]
ggplot(ju06_12,aes(x=log(stbeink_BUND),fill=steuerjahr))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
  geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
  geom_text(data=theils, position=position_dodge(width=9), aes(x = 10.5, y = 0.5, color=steuerjahr, label = paste("Theil:",round(theils$Theil,2))))+
  facet_wrap(~household,ncol=1)+
  scale_fill_manual(values=c("2006"="blue","2012"="red" )) +
  scale_color_manual(values=c("2006"="blue","2012"="red" )) +
  ggtitle("Jura: log net income by tax period and household situation")+
  xlab("log net income")+
  theme_bw()

# JURA Agegroups
p50s <- aggregate(log(ju06_12$stbeink_BUND)~ju06_12$agegroup+factor(ju06_12$steuerjahr),FUN=median,na.rm=TRUE)
names(p50s) <- c("agegroup","steuerjahr","log_income")
p50s <- p50s[order(p50s$agegroup),]
theils <- aggregate(ju06_12$stbeink_BUND~ju06_12$agegroup+factor(ju06_12$steuerjahr),FUN=Theil)
names(theils) <- c("agegroup","steuerjahr","Theil")
theils <- theils[order(theils$agegroup),]
ggplot(ju06_12,aes(x=log(stbeink_BUND),fill=steuerjahr))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
  geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
  geom_text(data=theils, position=position_dodge(width=9), aes(x = 10.5, y = 0.5, color=steuerjahr, label = paste("Theil:",round(theils$Theil,2))))+
  facet_wrap(~agegroup,ncol=1)+
  scale_fill_manual(values=c("2006"="blue","2012"="red" )) +
  scale_color_manual(values=c("2006"="blue","2012"="red" )) +
  ggtitle("Jura: log net income by tax period and agegroup")+
  xlab("log net income")+
  theme_bw()

# Jura Agegroups detailed
p50s <- aggregate(log(ju06_12$stbeink_BUND)~ju06_12$alterskategorie+factor(ju06_12$steuerjahr),FUN=median,na.rm=TRUE)
names(p50s) <- c("alterskategorie","steuerjahr","log_income")
p50s <- p50s[order(p50s$alterskategorie),]
theils <- aggregate(ju06_12$stbeink_BUND~ju06_12$alterskategorie+factor(ju06_12$steuerjahr),FUN=Theil)
names(theils) <- c("alterskategorie","steuerjahr","Theil")
theils <- theils[order(theils$alterskategorie),]
ggplot(ju06_12,aes(x=log(stbeink_BUND),fill=steuerjahr))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
  geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
  geom_text(data=theils, position=position_dodge(width=9), aes(x = 10.5, y = 0.5, color=steuerjahr, label = paste("Theil:",round(theils$Theil,2))))+
  facet_wrap(~alterskategorie,ncol=1)+
  scale_fill_manual(values=c("2006"="blue","2012"="red" )) +
  scale_color_manual(values=c("2006"="blue","2012"="red" )) +
  ggtitle("Jura: log net income by tax period and agegroup (detailed")+
  xlab("log net income")+
  theme_bw()


```

### Detailliertere Altersanalysen Basel

```{r}
bs91_11$single <- factor(bs91_11$household%in%c("Single women", "Single man", "Single mom", "Single dad"),labels=c("married","single"))
p50s <- aggregate(log(bs91_11$reineinkommen)~bs91_11$agegroup_det+factor(bs91_11$steuerjahr)+bs91_11$single,FUN=median,na.rm=TRUE)
names(p50s) <- c("agegroup_det","steuerjahr","single","log_income")
p50s <- p50s[order(p50s$agegroup_det),]
theils <- aggregate(bs91_11$reineinkommen~bs91_11$agegroup_det+factor(bs91_11$steuerjahr)+bs91_11$single,FUN=Theil)
names(theils) <- c("agegroup_det","steuerjahr","single","Theil")
theils <- theils[order(theils$agegroup_det),]

ggplot(theils, aes(x=agegroup_det, y=Theil,group=steuerjahr,color=steuerjahr))+geom_line(size=1)+
scale_color_manual(values=c("1991"="blue","2011"="red" ))+
facet_wrap(~single)+
theme_bw()
```

### Kontrafaktische Verteilung Basel

Wie würde 2011 in Basel aussehen wenn Alter und Haushaltsstruktur wie 1991 wären?

```{r cf}
# Dinardo (2002) beschreibt nochmal was in DiNardo Fortin Lemieux (1996) steht: http://www-personal.umich.edu/~jdinardo/bztalk5.pdf verwenden wir aber nicht, sondern entropy balancing (Hainmüller 2011)

# wir gewichten 2011 mit dem Inversen Propensity score.

# Datensatz ohne Missings erstellen
bs_nomiss <- na.omit(bs91_11)
bs_nomiss$T <- bs_nomiss$steuerjahr=="1991"
# gewichte durch entroy balancing ermitteln
fit <- glm(T~alterskategorie*household,data=bs_nomiss,family=binomial)
bs_nomiss$ps <- plogis(predict(fit))
bs_nomiss$w <- bs_nomiss$ps/(1-bs_nomiss$ps)
counterfactual <- bs_nomiss[bs_nomiss$steuerjahr=="2011",]
counterfactual$steuerjahr <- "2011 CF"
bs_nomiss$w<-1
counterfactual$w <- counterfactual$w/mean(counterfactual$w[counterfactual$steuerjahr=="2011 CF"])
bs_nomiss<-rbind(bs_nomiss,counterfactual)

#p50s <- aggregate(log(bs_nomiss$reineinkommen)~factor(bs_nomiss$steuerjahr),FUN=median,na.rm=TRUE)
#names(p50s) <- c("steuerjahr","log_income")
theils <- aggregate(bs_nomiss$reineinkommen~factor(bs_nomiss$steuerjahr),FUN=Theil)
names(theils) <- c("steuerjahr","Theil")
theils$w<-1
# den CF Theil müssen wir mit calcGEI() berechnen da Theil() keine Gewichte unterstützt
theils$Theil[theils$steuerjahr=="2011 CF"] <- calcGEI(x=counterfactual$reineinkommen,w=counterfactual$w,alpha=1)$ineq$index

ggplot(bs_nomiss,aes(x=log(reineinkommen),fill=steuerjahr,weight=w))+
  geom_density(aes(y=..density..),alpha = 0.5,position="identity")+
 #   geom_vline(data=p50s, aes(xintercept=log_income,color=steuerjahr))+
   geom_text(data=theils, position=position_stack(), aes(x = 3, y = 10000,color=steuerjahr, label = paste("Theil:",round(theils$Theil,3))))+
  scale_fill_manual(values=c("1991"="blue","2011"="red","2011 CF" = "orange")) +
  scale_color_manual(values=c("1991"="blue","2011"="red","2011 CF" = "orange")) +
    ggtitle("Basel: log net income 1991, 2011 and counterfactual")+
  xlab("log net income")+
  theme_bw()

```


